spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema: estimate
        jdbc:
          time_zone: UTC
    show-sql: true
app:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 86400000
    cookieName: talasila-jwt
