spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estimate
    username: estimate
    password: Estimate@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        schema: estimate
    show-sql: true
app:
  jwt:
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    expirationMs: 86400000
    cookieName: talasila-jwt
